security:
  jwt:
    secret: ${JWT_SECRET:myVerySecretKeyForJWTTokenGeneration2024MustBe256BitsMinimumForHS512AlgorithmToWorkProperlyWithSecureEncryption}
    expiration: 86400000  # 24 horas
    refresh-expiration: 604800000  # 7 dias